#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: agil

# Short bio or description (displayed in the header)
description: computer programmer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: a9il
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: agil_e
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-166024838-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://a9il.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: 

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.8.7

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-midnight

staticman_url: https://a9il-github-io-staticman.herokuapp.com/v2/entry/a9il/a9il.github.io/master/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LewVPUUAAAAAPq4o723rxD4ivF3cXCWr3F5D90X
  secret: mL0JWWl/PNG22M2yIlz/I8/6MOH0cpMBNOxMqD0ZzzD4VwIoyt0UCx0hmRQTJOXBqBid+L+rxiQzGGffuMrN2IwyTlcuxAH7JHvc4zID98/FWOyVU/JPB/tMrk0rn1KRUEupQMvY8g0nyR9nXPQk4lqETeC8qttqr7bc0VkSgVQ9P0BADEwSgn6rSWLJt7J03GsjOQETUptpoB/OiBZS309d0quzBvDaf1Ko2gt71Ii8PYCJrAE9bE9eQJ3lVL1fEUTWfan3EymeoGPUS2nsgy/tEDjcHUshlEVTlymTJibViwvqM1NAJfjjaEPJORQBQgoHzBchfq9kBtXR3aasGMJCgyl7yTg1+9NGgcSF3GTVTYpMVDTD+ZLu9CPPmABc0QkOLTyvD2QtcbMeyL4A18Ffkm10wj5284Keoyavi0G0MM8DP6hs37jbeGEdCBaN5A0Tif6FXJhOkmqv57JF4tomZ1t854vvN4gr8ieXztthG6IpSSPs+M/N6RVeC0lQRXzQ6bx+jVnMC9ZoIBnO5yfS/w2Sh/nlxVHA38OylXJIcq/vWGs+qxOZaP5X9Izf5ezBRMq9YYGeaQYqsqfvkBQCtj7Np6MI5M2omWs/a9oSQ5/QUJrcLkTQdnElEQMt6H7AA5189TUqfDK9oGPBiSD3l7/742tIO0X94kj43oY=
